org: chrisgrigg
app: widget
service: widget-server
frameworkVersion: '3'

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-plugin-typescript
custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      noStart: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    WIDGETS_TABLE: Widget-Items-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.WIDGETS_TABLE}"

functions:
  createWidget:
    handler: src/functions/index.handler
    events:
      - http:
          method: post
          path: create-widget
          cors: true
  getAllWidgets:
    handler: src/functions/index.handler
    events:
      - http:
          method: get
          path: get-widgets
          cors: true
  getWidget:
    handler: src/functions/index.handler
    events:
      - http:
          method: get
          path: get-widget/{id}
          cors: true
  updateWidget:
    handler: src/functions/index.handler
    events:
      - http:
          method: put
          path: update-widget/{id}
          cors: true
  deleteWidget:
    handler: src/functions/index.handler
    events:
      - http:
          method: delete
          path: delete-widget/{id}
          cors: true

resources:
  Resources:
    WidgetsListTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.WIDGETS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
